### ISSUE TITLE
Used name constants for neural network size

### ISSUE THREAD

**Issue by Beliavsky** [piotrbajdek/Fortran_AI#1]
In your code `gelu_att_8_8_8.f90` you hard code the network size `8` in many places. It would make the code more to flexible to define something like

`integer, parameter :: net_size = 8`

and use `net_size` instead of 8 in the code. The same suggestion applies to the other codes.

**Comment by piotrbajdek** [comment]
Thanks, @Beliavsky ! I've edited the code, incorporating `net_size` and making other necessary modifications. 🙂
